# Uncomment this line to define a global platform for your project
# platform :ios, "8.0"

target "FontingAwesome" do
  pod 'FontAwesomeKit', '~> 2.2.0'
  pod 'CWStatusBarNotification', '~> 2.3.3'
  
end

target "FontingAwesomeTests" do

end

